# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/windsome?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db-username}
    password: ${db-password}
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao-client-id}
            client-secret: ${kakao-client-secret}
            redirect-uri: "http://localhost:8080/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email
          naver:
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            redirect-uri: "http://localhost:8080/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

logging:
  level:
    p6spy: info

decorator:
  datasource:
    p6spy:
      enable-logging: true

# 상품 이미지 업로드 경로
productImgLocation: C:\shop\product

# 리소스 업로드 경로
uploadPath: file:\\\C:\shop\